Visualizacion de Datos

In [1]:
## Empece importando las librerias que tengo que utilizar para el desarrollo de mi reto

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
#Quise confirmar que mi base de datos que importe estaba en el mismo path que estaba trabajando.

In [4]:
%ls

 07_02_pie_box_scatter_bubble.ipynb   requierementsEXL
 Canada.xlsx                          requirements.txt
 datasets/                           'Reto Entregable 1.ipynb'
 estadistica-descriptiva.ipynb        runtime.txt
 movie_metadata.csv                   session_01/
 nhanes_2015_2016.csv                 welcome_binder.ipynb
 README.md

In [5]:
#Para poder abrir la base de datos tengo que utilizar panda para abrirlo dentro de un dataframe

In [6]:
df = pd.read_csv("movie_metadata.csv")

In [7]:
#Ya al asignar que tu dataframe sea tu base de datos abri el dataframe que me muestra los datos

In [8]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [9]:
#Note que en mi dataframe habian columnas que no influyen el analisis que voy a realizar por ende lo borre

In [10]:
df = pd.read_csv("movie_metadata.csv")

df.drop("color",
        axis=1,inplace=True,)
         
df.drop("duration",
        axis=1,inplace=True,)

df.drop("gross",
        axis=1,inplace=True,)

df.drop("movie_imdb_link",
        axis=1,inplace=True,)

df.drop("aspect_ratio",
        axis=1,inplace=True,)    

df.drop( "facenumber_in_poster",
        axis=1,inplace=True) 
df

df.head()

,director_name,num_critic_for_reviews,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,genres,actor_1_name,movie_title,num_voted_users,...,plot_keywords,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes
0,James Cameron,723.0,0.0,855.0,Joel David Moore,1000.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,...,avatar|future|marine|native|paraplegic,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,33000
1,Gore Verbinski,302.0,563.0,1000.0,Orlando Bloom,40000.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,...,goddess|marriage ceremony|marriage proposal|pi...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,0
2,Sam Mendes,602.0,0.0,161.0,Rory Kinnear,11000.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,...,bomb|espionage|sequel|spy|terrorist,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,85000
3,Christopher Nolan,813.0,22000.0,23000.0,Christian Bale,27000.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,...,deception|imprisonment|lawlessness|police offi...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,164000
4,Doug Walker,NaN,131.0,NaN,Rob Walker,131.0,Documentary,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,0

La variable de interes de mi base de datos es "imdb_score" lo cual se identifica como la valoracion de gusto de la pelicula en este sitio en especifico. Es el sitio mas utilizado para hacer el rank de peliculas que hayan salido por lo cual le dan la importancia. Mi proposito con esta base de datos es descubrir la importancia de las variables "num_critic_for_reviews", "budget", "num_voted_users", "actor_1_name", y como impactan el "imbd_score".